spring:
    profiles: staging
    datasource:
#        platform: mysql
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://127.0.0.1:3306/sample?useSSL=false&characterEncoding=UTF-8
#        username: root
#        password: passw0rd
        platform: oracle
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@192.168.0.21:1521:orcl
        username: GEEKLY_CP3
        password: GEEKLY_CP3
    mail:
        default-encoding: ISO-2022-JP
        protocol: smtp
        host: 127.0.0.1
        port: 25
        username: test
        password: test
        properties:
            mail:
                from: from@test.com
logging:
    # ログ出力先を指定する
    file: /var/log/sample/app.log
    level:
        org.springframework.web: INFO

####
# アプリケーションの設定
application:
    fileUploadLocation: build/sample